service: carts

frameworkVersion: "2"
# variablesResolutionMode: 20210219

useDotenv: true

plugins:
  - serverless-webpack
  - serverless-dynamodb-local
  - serverless-offline-dotenv
  - serverless-offline

custom:
  webpack:
    webpackConfig: "./webpack.config.js"
    includeModules:
      forceExclude:
        - aws-sdk
    packager: "npm"
  serverless-offline:
    httpPort: 4000
    ignoreJWTSignature: true

provider:
  name: aws
  region: eu-central-1
  # profile: swexception
  runtime: nodejs12.x
  lambdaHashingVersion: "20201221"
  stage: ${opt:stage, 'dev'}

  apiGateway:
    restApiId: 95kq9eggu9
    restApiRootResourceId: zsd84g8moe

  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: "1"
    REGION: ${self:provider.region}
    SERVICES: ${env:SERVICES}

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:*
            - s3:*
          Resource: "*"

functions:
  getCart:
    handler: "src/handlers/getCart.HANDLER"
    events:
      - http:
          path: /cart
          method: GET
          cors: true
  deleteCart:
    handler: "src/handlers/deleteCart.HANDLER"
    events:
      - http:
          path: /cart
          method: DELETE
          cors: true
  addToCart:
    handler: "src/handlers/addToCart.HANDLER"
    events:
      - http:
          path: /cart/
          method: POST
          cors: true
  removeFromCart:
    handler: "src/handlers/removeFromCart.HANDLER"
    events:
      - http:
          path: /cart/{id}
          method: DELETE
          cors: true

resources:
  Resources:
    #dynamodb tables
    CartsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: carts
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: "S"
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST